name: reel illusion films
favicon: null
layout_spectrum: 0.6331595762167126
typography_spectrum: 0.7614269608166069
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4867778813932091
  lightness: 0.972022355068475
  saturation: 0.772771981311962
  rhythmicContrast: 0.026204298250377178
purpose: []
